const ROOT=document.documentElement.dataset.apiBase.replace(/\/$/,'');const API=location.hostname==='bay-trends.replit.app'?'':'/api/market';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let current=null,currentQuery='',toastTimer;
let watch=JSON.parse(localStorage.getItem('collecti-watchlist')||'[]'),compare=JSON.parse(localStorage.getItem('collecti-compare')||'[]');
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};const money=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}):'—';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));
async function request(path){const r=await fetch(API+path,{credentials:'include'});if(!r.ok)throw new Error((await r.text())||`Request failed (${r.status})`);return r.json()}
const salesOf=d=>d?.recentSales||d?.sales||d?.soldListings||[];const listingsOf=d=>d?.activeListings||d?.listings||d?.currentListings||[];
function prices(d){return salesOf(d).map(x=>Number(x.price||x.soldPrice||x.totalPrice)).filter(Number.isFinite)}
function valueOf(d){const p=prices(d);return Number(d?.estimatedValue||d?.averagePrice||d?.marketValue||(p.length?p.reduce((a,b)=>a+b,0)/p.length:0))}
function rangeOf(d){const p=prices(d).sort((a,b)=>a-b);return [Number(d?.priceRange?.min||d?.lowPrice||p[0]||0),Number(d?.priceRange?.max||d?.highPrice||p[p.length-1]||0)]}
function confidenceOf(d){return d?.confidenceScore??d?.confidence??(salesOf(d).length>=20?90:salesOf(d).length>=8?76:salesOf(d).length?58:35)}
function normalized(q,d){const [low,high]=rangeOf(d);return{query:q,value:valueOf(d),low,high,sales:salesOf(d).length,confidence:confidenceOf(d),direction:d?.trend||d?.marketTrend||d?.priceTrend||'Stable',raw:d,date:new Date().toISOString()}}
function setConnection(ok,text){$('#connection').classList.toggle('online',ok);$('#connection span').textContent=text||(ok?'Live market data':'Connection unavailable')}
function table(items,type){if(!items.length)return'<div class="empty"><strong>No observations returned</strong>Try a more exact title, grade, set, or issue number.</div>';return`<div style="overflow:auto"><table><thead><tr><th>Title</th><th>Condition</th><th>Price</th><th>Marketplace</th><th>${type==='sales'?'Sold':'Observed'}</th></tr></thead><tbody>${items.slice(0,30).map(x=>`<tr><td>${esc(x.title||x.name||'Marketplace item')}</td><td>${esc(x.condition||x.grade||'—')}</td><td><b>${money(x.price||x.soldPrice||x.totalPrice)}</b></td><td>${esc(x.platform||x.marketplace||'eBay')}</td><td>${esc((x.soldDate||x.endDate||x.listingDate||x.date||'—').toString().slice(0,10))}</td></tr>`).join('')}</tbody></table></div>`}
function renderReport(q,data){current=normalized(q,data);currentQuery=q;$('#analysisEmpty').hidden=true;$('#analysisResult').hidden=false;$('#reportTitle').textContent=data?.item?.name||data?.name||data?.title||q;$('#reportSubtitle').textContent=`${data?.rawDataCount??current.sales} marketplace observations • generated ${new Date().toLocaleDateString()}`;$('#mValue').textContent=money(current.value);$('#mRange').textContent=current.low||current.high?`${money(current.low)}–${money(current.high)}`:'—';$('#mSales').textContent=current.sales.toLocaleString();$('#mConfidence').textContent=`${Math.round(Number(current.confidence))}%`;
const p=prices(data),max=Math.max(...p,1);$('#priceChart').innerHTML=(p.length?p.slice(-24):[22,35,28,48,42,55,70,61,78,68,82,90]).map((v,i)=>`<i style="height:${Math.max(7,v/max*100)}%" title="${money(v)}"></i>`).join('');
const listCount=listingsOf(data).length,liquidity=Math.min(100,Math.round(current.sales/Math.max(1,listCount+current.sales)*170)),confidence=Math.min(100,Number(current.confidence)||0),sample=Math.min(100,current.sales*4);$('#signals').innerHTML=[['Confidence',confidence],['Sales sample',sample],['Liquidity',liquidity],['Listing depth',Math.min(100,listCount*4)]].map(([l,v])=>`<div><div class="bar-label"><b>${l}</b><span>${Math.round(v)}%</span></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');
$('#salesTab').innerHTML=table(salesOf(data),'sales');$('#listingsTab').innerHTML=table(listingsOf(data),'listings');const insights=data?.insights||data?.analysis||data?.summary||data?.aiSummary||'The report did not return a written market summary. Review the observed sales, listing depth, and confidence before making a transaction decision.';$('#insightsTab').innerHTML=`<div style="line-height:1.75;color:var(--muted);padding:8px 3px;white-space:pre-wrap">${esc(typeof insights==='string'?insights:JSON.stringify(insights,null,2))}</div>`;setConnection(true)}
async function analyze(q){q=q.trim();if(q.length<3)return;const btn=$('#analyzeButton');btn.disabled=true;btn.textContent='Analyzing…';setConnection(false,'Collecting market data');$('#analysisEmpty').hidden=false;$('#analysisEmpty').innerHTML='<strong>Building market report…</strong>Reviewing listings, recent transactions and price signals.';try{const data=await request(`/api/analysis/${encodeURIComponent(q)}`);renderReport(q,data);history.replaceState(null,'',`?q=${encodeURIComponent(q)}`)}catch(e){setConnection(false);$('#analysisEmpty').innerHTML='<strong>Analysis unavailable</strong>The live backend could not be reached from this host. Deploy this interface with the analyzer API or allow its origin.';toast(e.message)}finally{btn.disabled=false;btn.textContent='Analyze market'}}
$('#analysisForm').onsubmit=e=>{e.preventDefault();analyze($('#query').value)};$$('.suggestion').forEach(b=>b.onclick=()=>{$('#query').value=b.textContent;analyze(b.textContent)});$('#focusSearch').onclick=()=>{nav('analyze');$('#query').focus()};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['sales','listings','insights'].forEach(k=>$(`#${k}Tab`).hidden=k!==b.dataset.tab)});
function saveLocal(){localStorage.setItem('collecti-watchlist',JSON.stringify(watch));localStorage.setItem('collecti-compare',JSON.stringify(compare));renderWatch();renderCompare()}
$('#addWatch').onclick=()=>{if(!current)return;if(!watch.some(x=>x.query===current.query))watch.unshift(current);saveLocal();toast('Added to your watchlist.')};$('#addCompare').onclick=()=>{if(!current)return;if(compare.some(x=>x.query===current.query))return toast('Already in comparison.');if(compare.length>=3)return toast('Comparison is limited to three items.');compare.push(current);saveLocal();toast('Added to comparison.')};
function reportCard(x){return`<article class="card item-card"><div class="item-media">${esc((x.query||'?').slice(0,1).toUpperCase())}</div><div class="item-body"><h3>${esc(x.query)}</h3><div class="price">${money(x.value)}</div><p class="muted" style="font-size:11px">${x.sales} sales • ${Math.round(x.confidence)}% confidence</p><button class="btn" data-analyze="${esc(x.query)}">Run again</button></div></article>`}
function renderWatch(){const g=$('#watchGrid');g.innerHTML=watch.length?watch.map(reportCard).join(''):'<div class="card empty"><strong>Your watchlist is empty</strong>Analyze an item and select “Watch.”</div>';$$('[data-analyze]').forEach(b=>b.onclick=()=>{nav('analyze');$('#query').value=b.dataset.analyze;analyze(b.dataset.analyze)})}
function renderCompare(){const body=$('#compareTable');$('#compareStrip').innerHTML=compare.map(x=>`<span class="compare-pill">${esc(x.query)}</span>`).join('');body.innerHTML=compare.length?compare.map(x=>`<tr><td><b>${esc(x.query)}</b></td><td>${money(x.value)}</td><td>${money(x.low)}–${money(x.high)}</td><td>${x.sales}</td><td>${Math.round(x.confidence)}%</td><td>${esc(x.direction)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Add reports from the Analyze view.</td></tr>'}
$('#clearCompare').onclick=()=>{compare=[];saveLocal()};$('#exportWatchlist').onclick=()=>download('collecti-watchlist.json',JSON.stringify(watch,null,2),'application/json');$('#exportReport').onclick=()=>current&&download(`${current.query.replace(/[^a-z0-9]+/gi,'-')}-market-report.json`,JSON.stringify(current.raw,null,2),'application/json');function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function loadCategories(){const grid=$('#categoryGrid');grid.innerHTML='<div class="card empty">Loading categories…</div>';try{const data=await request('/api/categories'),cats=Array.isArray(data)?data:(data?.categories||[]);setConnection(true);grid.innerHTML=cats.map((c,i)=>{const name=typeof c==='string'?c:c.name;return`<button class="card" data-category="${esc(name)}" style="color:inherit;text-align:left;cursor:pointer"><div class="eyebrow">Category ${String(i+1).padStart(2,'0')}</div><h2 style="font:700 18px Manrope;margin:9px 0">${esc(name)}</h2><span class="muted">Browse items →</span></button>`}).join('')||'<div class="card empty">No categories returned.</div>';$$('[data-category]').forEach(b=>b.onclick=()=>loadCategory(b.dataset.category))}catch(e){setConnection(false);grid.innerHTML='<div class="card empty">Categories are unavailable from this host.</div>'}}
async function loadCategory(name){const box=$('#categoryItems');box.innerHTML='<div class="card empty">Loading items…</div>';try{const data=await request(`/api/categories/${encodeURIComponent(name)}/items`),items=Array.isArray(data)?data:(data?.items||[]);box.innerHTML=`<div class="heading"><div><h1 style="font-size:28px">${esc(name)}</h1><p>${items.length} items available for analysis</p></div></div><div class="grid result-grid">${items.slice(0,30).map(x=>`<button class="card" data-item-query="${esc(x.name||x.title)}" style="color:inherit;text-align:left;cursor:pointer"><h3>${esc(x.name||x.title)}</h3><strong class="price">${money(x.currentPrice||x.averagePrice||x.price)}</strong><p class="muted">Analyze market →</p></button>`).join('')}</div>`;$$('[data-item-query]').forEach(b=>b.onclick=()=>{nav('analyze');$('#query').value=b.dataset.itemQuery;analyze(b.dataset.itemQuery)})}catch(e){box.innerHTML='<div class="card empty">Unable to load category items.</div>'}}
$('#refreshCategories').onclick=loadCategories;renderWatch();renderCompare();loadCategories();const initial=new URLSearchParams(location.search).get('q');if(initial){$('#query').value=initial;analyze(initial)}else setConnection(true,'Ready to analyze');
