const ROOT=document.documentElement.dataset.apiBase.replace(/\/$/,'');
const API=location.hostname==='collecti-agent.replit.app'?'':'/api/agent';
const state={searches:[],stats:{},created:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let toastTimer;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
const num=n=>Number(n||0).toLocaleString();
async function request(path,options={}){const r=await fetch(API+path,{credentials:'include',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(!r.ok)throw new Error((await r.text())||`Request failed (${r.status})`);return r.status===204?null:r.json()}
function setConnection(ok){$('#connection').classList.toggle('online',ok);$('#connection span').textContent=ok?'Live data':'Offline preview'}
function searchName(s){return s.title||s.query||s.description||'Untitled discovery'}
function searchRow(s){const status=(s.status||'ready').toLowerCase();return `<div class="search-row" data-id="${s.id}"><div class="icon">⌕</div><div><strong>${esc(searchName(s))}</strong><span>${esc((s.category||'other').replaceAll('-',' '))} • ${new Date(s.createdAt||Date.now()).toLocaleDateString()}</span></div><span class="badge ${status==='failed'?'failed':''}">${esc(status)}</span></div>`}
function render(){const searches=state.searches||[];$('#statSearches').textContent=num(state.stats.totalSearches??searches.length);$('#statItems').textContent=num(state.stats.totalItems??state.stats.itemsFound??searches.reduce((a,s)=>a+(s.resultCount||s.itemsFound||0),0));const saved=searches.filter(s=>s.isSaved||s.saved);$('#statSaved').textContent=num(saved.length);const complete=searches.filter(s=>s.status==='complete').length;$('#statRate').textContent=searches.length?Math.round(complete/searches.length*100)+'%':'—';
$('#recentSearches').innerHTML=searches.length?searches.slice(0,6).map(searchRow).join(''):'<div class="empty"><strong>No searches yet</strong>Start an AI discovery mission.</div>';
renderSearches();const counts={};searches.forEach(s=>counts[s.category||'other']=(counts[s.category||'other']||0)+1);const max=Math.max(1,...Object.values(counts));$('#categoryBars').innerHTML=Object.keys(counts).length?Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([k,v])=>`<div><div class="bar-label"><b>${esc(k.replaceAll('-',' '))}</b><span>${v}</span></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<div class="empty">No category data yet.</div>';
$('#marketStats').innerHTML=[['Active categories',Object.keys(counts).length],['Completed missions',complete],['Saved watches',saved.length],['Failed searches',searches.filter(s=>s.status==='failed').length]].map(([l,v])=>`<div class="card stat"><div class="label">${l}</div><strong>${v}</strong></div>`).join('');
const vals=Object.values(counts);$('#activityChart').innerHTML=(vals.length?vals:[2,4,3,7,5,8,6,9,7,10,8,11]).map(v=>`<i style="height:${Math.max(8,v/Math.max(...(vals.length?vals:[11]))*100)}%" title="${v} searches"></i>`).join('');
}
function renderSearches(){const q=$('#searchFilter')?.value.toLowerCase()||'',status=$('#statusFilter')?.value||'';const list=state.searches.filter(s=>(!q||searchName(s).toLowerCase().includes(q)||String(s.category).toLowerCase().includes(q))&&(!status||s.status===status));$('#allSearches').innerHTML=list.length?list.map(searchRow).join(''):'<div class="empty"><strong>No matching searches</strong>Try another filter.</div>';}
async function load(){try{const [searches,stats]=await Promise.all([request('/api/searches'),request('/api/searches/stats').catch(()=>({}))]);state.searches=Array.isArray(searches)?searches:(searches?.searches||[]);state.stats=stats||{};setConnection(true);render()}catch(e){setConnection(false);toast('Live API unavailable. Host this interface with the CollectiAgent backend or allow its origin.');render()}}
$('#refreshDashboard').onclick=load;$('#searchFilter').oninput=renderSearches;$('#statusFilter').onchange=renderSearches;
$('#discoveryForm').onsubmit=async e=>{e.preventDefault();const btn=$('#createSearch'),data=Object.fromEntries(new FormData(e.currentTarget));Object.keys(data).forEach(k=>data[k]===''&&delete data[k]);btn.disabled=true;btn.textContent='Creating discovery…';try{const created=await request('/api/searches',{method:'POST',body:JSON.stringify(data)});state.created=created;state.searches.unshift(created);$('#createdSearch').classList.add('active');$('#createdCopy').textContent=`“${searchName(created)}” is ready. Run it now, save it for monitoring, or inspect its live results.`;render();toast('Discovery mission created.');try{await request(`/api/searches/${created.id}/run`,{method:'POST'});toast('Discovery is now running.')}catch{}}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent='Create & run discovery'}};
$('#openOriginal').onclick=()=>state.created&&open(`${ROOT}/search/${state.created.id}`,'_blank');$('#runAgain').onclick=async()=>{if(!state.created)return;try{await request(`/api/searches/${state.created.id}/run-now`,{method:'POST'});toast('Search queued.')}catch(e){toast(e.message)}};$('#saveCreated').onclick=async()=>{if(!state.created)return;try{state.created=await request(`/api/searches/${state.created.id}/save`,{method:'PATCH',body:JSON.stringify({isSaved:true})});toast('Watch saved.');load()}catch(e){toast(e.message)}};
$('#openSaved').onclick=()=>{nav('searches');$('#statusFilter').value='';$('#searchFilter').value='';renderSearches()};
$('#exportSearches').onclick=()=>{const rows=[['Title','Category','Status','Created'],...state.searches.map(s=>[searchName(s),s.category,s.status,s.createdAt])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='collectiagent-searches.csv';a.click();URL.revokeObjectURL(a.href)};
load();
